In [144]:
import pandas as pd
from sklearn.preprocessing import Imputer
import numpy as np

db = pd.read_csv("database.csv")
print(db.describe())

          sessionNo     startHour  startWeekday      duration        cCount  \
count  50000.000000  50000.000000  50000.000000  50000.000000  50000.000000
mean   25000.500000     14.367060      5.923140   1465.728502     20.233700
std    14433.901067      4.638547      0.795063   2314.980566     28.430273
min        1.000000      0.000000      5.000000      0.000000      0.000000
25%    12500.750000     11.000000      5.000000    217.926750      4.000000
50%    25000.500000     15.000000      6.000000    686.784500     10.000000
75%    37500.250000     18.000000      7.000000   1726.262750     24.000000
max    50000.000000     23.000000      7.000000  21580.092000    200.000000

             bCount        rCount  bMinPriceVariance  bMaxPriceVariance  \
count  50000.000000  50000.000000       5.000000e+04       5.000000e+04
mean       3.207580      0.597040       9.167735e+02       9.167735e+02
std        3.549983      0.490498       1.388429e+04       1.388429e+04
min        0.000000      0.000000       0.000000e+00       0.000000e+00
25%        1.000000      0.000000       0.000000e+00       0.000000e+00
50%        2.000000      1.000000       0.000000e+00       0.000000e+00
75%        4.000000      1.000000       6.656812e+00       6.656812e+00
max      108.000000      1.000000       1.388889e+06       1.388889e+06

       bMeanVariance  cMeanVariance
count   5.000000e+04   5.000000e+04
mean    9.167735e+02   9.167735e+02
std     1.388429e+04   1.388429e+04
min     0.000000e+00   0.000000e+00
25%     0.000000e+00   0.000000e+00
50%     0.000000e+00   0.000000e+00
75%     6.656812e+00   6.656812e+00
max     1.388889e+06   1.388889e+06

In [145]:
db = db.replace({'?': np.nan})
print(db)

       sessionNo  startHour  startWeekday  duration  cCount cMinPrice  \
0              1          6             5    39.887       1     59.99
1              2          6             5    94.469       0       NaN
2              3          6             5   341.613      11      9.99
3              4          6             5    42.812       4      4.99
4              5          6             5  2816.046      45     12.99
5              6          6             5     0.000       3     99.99
6              7          6             5   973.887      15         3
7              8          6             5     0.000       1     59.99
8              9          6             5   550.968       2    499.99
9             10          6             5  1106.575      19         5
10            11          6             5   172.179       0       NaN
11            12          6             5  1540.895      21      5.99
12            13          6             5   279.537       0       NaN
13            14          6             5   130.534       4     14.99
14            15          6             5  1208.612       4    199.99
15            16          6             5  6826.536     154     79.99
16            17          6             5   153.267       0       NaN
17            18          6             5   441.648       7     19.99
18            19          6             5  4714.493     162       0.8
19            20          6             5  7647.510      11     49.99
20            21          6             5   152.401       3     14.99
21            22          6             5  3784.495      81      9.99
22            23          6             5    26.997       1      6.99
23            24          6             5  8484.409      44      4.99
24            25          6             5    15.524       1     59.99
25            26          6             5  5306.594     127      7.99
26            27          6             5  8095.292      69         3
27            28          6             5   660.644      23     14.99
28            29          6             5  1850.449      27      9.99
29            30          6             5   492.582      11     19.99
...          ...        ...           ...       ...     ...       ...
49970      49971         18             7   357.766      10     17.99
49971      49972         18             7  2252.500      14     14.99
49972      49973         18             7  1294.350      32      9.99
49973      49974         18             7  1832.336      42        10
49974      49975         18             7  1183.038      17         5
49975      49976         18             7  1865.295      32     29.99
49976      49977         18             7  2000.112      11     19.99
49977      49978         18             7   430.767       5     29.99
49978      49979         18             7   309.797       1     29.99
49979      49980         18             7  3883.236      10      8.95
49980      49981         18             7  1913.826       8     29.95
49981      49982         18             7   429.351      16     29.99
49982      49983         18             7   817.510      17     14.99
49983      49984         18             7  1946.042      16     14.96
49984      49985         18             7  4429.860      39      9.99
49985      49986         18             7   278.365       4      9.99
49986      49987         18             7   336.390      13     19.99
49987      49988         18             7   367.494       8     19.99
49988      49989         18             7    10.306       1      6.99
49989      49990         18             7   228.902       8      9.99
49990      49991         18             7  3895.061      47         3
49991      49992         18             7   389.549      16      5.99
49992      49993         18             7  4113.213      69      9.99
49993      49994         18             7  1294.397      53      3.99
49994      49995         18             7   572.544      22      9.99
49995      49996         18             7  7271.812     197      6.99
49996      49997         18             7   667.219       8     70.99
49997      49998         18             7  5988.882      77      9.99
49998      49999         18             7   715.341       7        59
49999      50000         18             7    82.943       1      6.99

      cMaxPrice cSumPrice  bCount bMinPrice  ...  payments  age address  \
0         59.99     59.99       1     59.99  ...         1   43       1
1           NaN       NaN       0       NaN  ...       NaN  NaN     NaN
2         29.99    109.95       2      9.99  ...        12   45       1
3          4.99     19.96       1      4.99  ...       NaN  NaN     NaN
4        179.95   1093.72       4     19.99  ...         1   46       1
5           169    398.98       3     99.99  ...       NaN  NaN     NaN
6            40       137       3         3  ...        10   31       2
7         59.99     59.99       1     59.99  ...        10   21       2
8        499.99    999.98       1    499.99  ...       NaN  NaN     NaN
9         24.99    246.11       2        12  ...        23   51       2
10          NaN       NaN       0       NaN  ...       NaN  NaN     NaN
11        59.99    456.77      11      5.99  ...        11   86       2
12          NaN       NaN       0       NaN  ...       NaN  NaN     NaN
13        29.99     59.97       1     14.99  ...       NaN  NaN     NaN
14      1999.99   3098.97       1    199.99  ...       NaN  NaN     NaN
15      2999.99  88427.55       4    199.99  ...       NaN  NaN     NaN
16          NaN       NaN       0       NaN  ...       NaN  NaN     NaN
17        29.99    199.93       2     29.99  ...         1   52       2
18        34.99   1445.19      15      1.99  ...         2   32       2
19       499.99   2199.91       1     49.99  ...        11   58       2
20        14.99     44.97       1     14.99  ...        34   51       2
21       119.95   2292.44       8      9.99  ...       NaN  NaN     NaN
22         6.99      6.99       1      6.99  ...       NaN  NaN     NaN
23        19.99     205.6       5         6  ...        15   38       2
24        59.99     59.99       1     59.99  ...       NaN  NaN     NaN
25        74.95   3673.21      11     14.99  ...       NaN  NaN     NaN
26         49.9    976.07       5     12.99  ...        10   38       2
27        33.99    617.77       3     24.99  ...         8   31       2
28        71.96   1400.63       2      9.99  ...       NaN  NaN     NaN
29        44.99    255.91       2     27.99  ...         0   39       2
...         ...       ...     ...       ...  ...       ...  ...     ...
49970     19.99     95.95       2     17.99  ...         2   41       2
49971     49.99    334.78       1     19.99  ...       NaN  NaN     NaN
49972     29.99    596.18       6      9.99  ...         3   56       2
49973     79.95    630.62       0       NaN  ...        19   56       1
49974    199.99     430.9       4      9.99  ...         0   47       2
49975     29.99    959.68       9     29.99  ...         4   48       2
49976       749   5730.98       2     19.99  ...       NaN  NaN     NaN
49977    299.99    419.95       2     29.99  ...       NaN  NaN     NaN
49978     29.99     29.99       1     29.99  ...        14   37       1
49979      11.9     71.13       3      8.95  ...        11   55       1
49980     34.99    159.83       2     29.95  ...       213  NaN       1
49981     29.99    479.84       5     29.99  ...         1   52       2
49982     24.99    299.85       3     14.99  ...        13   48       2
49983     24.99    262.82       2     14.99  ...       NaN  NaN     NaN
49984     99.99   1301.41       8      9.99  ...         2   48       2
49985     19.99     59.96       4      9.99  ...         4   27       2
49986    199.99    239.97       1     19.99  ...        29   43       2
49987     19.99    159.92       1     19.99  ...       NaN  NaN     NaN
49988      6.99      6.99       1      6.99  ...         0   53       1
49989     19.99    115.92       8      9.99  ...        13   41       2
49990     29.99     449.8       4         5  ...        13   58       2
49991      9.99    127.84       4      5.99  ...       NaN  NaN     NaN
49992     24.99    971.31      15      9.99  ...         0   54       2
49993        65   1354.34       6     14.99  ...       NaN  NaN     NaN
49994     19.99     319.6       2      9.99  ...         2   42       2
49995     59.99   4315.03      13      9.99  ...       NaN  NaN     NaN
49996     89.99    667.88       1     89.99  ...       NaN  NaN     NaN
49997    149.99   5253.28       3     49.95  ...       NaN  NaN     NaN
49998    649.99   1159.95       1     89.99  ...         0   24       1
49999      6.99      6.99       1      6.99  ...         0   53       1

      lastOrder rCount bMinPriceVariance bMaxPriceVariance bMeanVariance  \
0            49      0      0.000000e+00      0.000000e+00  0.000000e+00
1           NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
2            11      1      6.400000e+01      6.400000e+01  6.400000e+01
3           NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
4            40      1      1.447959e+01      1.447959e+01  1.447959e+01
5           NaN      1      2.000000e+02      2.000000e+02  2.000000e+02
6            10      1      0.000000e+00      0.000000e+00  0.000000e+00
7            57      0      0.000000e+00      0.000000e+00  0.000000e+00
8           NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
9            24      1      0.000000e+00      0.000000e+00  0.000000e+00
10          NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
11           37      1      5.706447e-01      5.706447e-01  5.706447e-01
12          NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
13          NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
14          NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
15          NaN      1      0.000000e+00      0.000000e+00  0.000000e+00
16          NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
17          189      1      0.000000e+00      0.000000e+00  0.000000e+00
18          276      1      4.986150e-02      4.986150e-02  4.986150e-02
19           61      0      0.000000e+00      0.000000e+00  0.000000e+00
20           23      0      0.000000e+00      0.000000e+00  0.000000e+00
21          NaN      1      4.855556e+01      4.855556e+01  4.855556e+01
22          NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
23           37      1      1.339349e-01      1.339349e-01  1.339349e-01
24          NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
25          NaN      1      5.269867e+01      5.269867e+01  5.269867e+01
26          151      1      7.840000e+00      7.840000e+00  7.840000e+00
27          109      1      6.172840e+00      6.172840e+00  6.172840e+00
28          NaN      1      2.659999e+02      2.659999e+02  2.659999e+02
29           36      1      0.000000e+00      0.000000e+00  0.000000e+00
...         ...    ...               ...               ...           ...
49970       243      1      0.000000e+00      0.000000e+00  0.000000e+00
49971       NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
49972       280      1      1.992889e+01      1.992889e+01  1.992889e+01
49973        35      0      0.000000e+00      0.000000e+00  0.000000e+00
49974       488      1      0.000000e+00      0.000000e+00  0.000000e+00
49975        43      1      0.000000e+00      0.000000e+00  0.000000e+00
49976       NaN      1      6.285986e+04      6.285986e+04  6.285986e+04
49977       NaN      1      0.000000e+00      0.000000e+00  0.000000e+00
49978         6      0      0.000000e+00      0.000000e+00  0.000000e+00
49979        62      1      1.560250e-01      1.560250e-01  1.560250e-01
49980         5      1      0.000000e+00      0.000000e+00  0.000000e+00
49981        36      1      1.262177e-29      1.262177e-29  1.262177e-29
49982        50      1      0.000000e+00      0.000000e+00  0.000000e+00
49983       NaN      1      0.000000e+00      0.000000e+00  0.000000e+00
49984        51      1      3.876543e+02      3.876543e+02  3.876543e+02
49985        32      1      0.000000e+00      0.000000e+00  0.000000e+00
49986         7      0      0.000000e+00      0.000000e+00  0.000000e+00
49987       NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
49988        34      0      0.000000e+00      0.000000e+00  0.000000e+00
49989        41      1      0.000000e+00      0.000000e+00  0.000000e+00
49990       164      1      7.780017e+00      7.780017e+00  7.780017e+00
49991       NaN      1      0.000000e+00      0.000000e+00  0.000000e+00
49992        45      1      2.221074e+00      2.221074e+00  2.221074e+00
49993       NaN      1      1.775148e+01      1.775148e+01  1.775148e+01
49994         9      1      2.204480e+01      2.204480e+01  2.204480e+01
49995       NaN      1      8.740895e-06      8.740895e-06  8.740895e-06
49996       NaN      0      0.000000e+00      0.000000e+00  0.000000e+00
49997       NaN      1      2.240036e+01      2.240036e+01  2.240036e+01
49998         4      0      0.000000e+00      0.000000e+00  0.000000e+00
49999        34      0      0.000000e+00      0.000000e+00  0.000000e+00

      cMeanVariance order
0      0.000000e+00     y
1      0.000000e+00     y
2      6.400000e+01     y
3      0.000000e+00     n
4      1.447959e+01     y
5      2.000000e+02     n
6      0.000000e+00     y
7      0.000000e+00     n
8      0.000000e+00     y
9      0.000000e+00     n
10     0.000000e+00     y
11     5.706447e-01     y
12     0.000000e+00     y
13     0.000000e+00     n
14     0.000000e+00     n
15     0.000000e+00     y
16     0.000000e+00     n
17     0.000000e+00     y
18     4.986150e-02     y
19     0.000000e+00     n
20     0.000000e+00     y
21     4.855556e+01     y
22     0.000000e+00     n
23     1.339349e-01     y
24     0.000000e+00     n
25     5.269867e+01     y
26     7.840000e+00     n
27     6.172840e+00     y
28     2.659999e+02     n
29     0.000000e+00     y
...             ...   ...
49970  0.000000e+00     y
49971  0.000000e+00     n
49972  1.992889e+01     y
49973  0.000000e+00     n
49974  0.000000e+00     y
49975  0.000000e+00     y
49976  6.285986e+04     n
49977  0.000000e+00     n
49978  0.000000e+00     y
49979  1.560250e-01     n
49980  0.000000e+00     y
49981  1.262177e-29     y
49982  0.000000e+00     y
49983  0.000000e+00     y
49984  3.876543e+02     y
49985  0.000000e+00     y
49986  0.000000e+00     y
49987  0.000000e+00     n
49988  0.000000e+00     n
49989  0.000000e+00     y
49990  7.780017e+00     y
49991  0.000000e+00     n
49992  2.221074e+00     n
49993  1.775148e+01     y
49994  2.204480e+01     n
49995  8.740895e-06     y
49996  0.000000e+00     n
49997  2.240036e+01     n
49998  0.000000e+00     n
49999  0.000000e+00     n

[50000 rows x 29 columns]

In [177]:
values = {
    'cMinPrice': db['cMinPrice'].astype(float).mode(),
    'cMaxPrice': db['cMaxPrice'].astype(float).mode(),
    'cSumPrice': db['cSumPrice'].astype(float).mode(),
    'bMinPrice': db['bMinPrice'].astype(float).mode(),
    'bMaxPrice': db['bMaxPrice'].astype(float).mode(),
    'bSumPrice': db['bSumPrice'].astype(float).mode(),
    'bStep': db['bStep'].astype(float).mode()[0],
    'onlineStatus': db['onlineStatus'].mode()[0],
    'availability': db['availability'].mode()[0],
    'customerNo': db['customerNo'].mode()[0],
    'maxVal': db['maxVal'].mode()[0],
    'customerScore': db['customerScore'].mode()[0],
    'accountLifetime': db['accountLifetime'].mode()[0],
    'payments': db['payments'].astype(float).mode()[0],
    'age': db['age'].astype(float).mode()[0],
    'address': db['address'].mode()[0],
    'lastOrder': db['lastOrder'].mode()[0],
}
db_mode = db.fillna(values)
db_mode.to_csv('database_mode.csv')

In [178]:
values = {
    'cMinPrice': db['cMinPrice'].astype(float).mode(),
    'cMaxPrice': db['cMaxPrice'].astype(float).mode(),
    'cSumPrice': db['cSumPrice'].astype(float).mode(),
    'bMinPrice': db['bMinPrice'].astype(float).mode(),
    'bMaxPrice': db['bMaxPrice'].astype(float).mode(),
    'bSumPrice': db['bSumPrice'].astype(float).mode(),
    'bStep': db['bStep'].astype(float).mode()[0],
    'onlineStatus': 'desconhecido',
    'availability': 'desconhecido',
    'customerNo': 'desconhecido',
    'maxVal': db['maxVal'].mode()[0],
    'customerScore': db['customerScore'].mode()[0],
    'accountLifetime': db['accountLifetime'].mode()[0],
    'payments': db['payments'].astype(float).mode()[0],
    'age': db['age'].astype(float).mode()[0],
    'address': db['address'].mode()[0],
    'lastOrder': db['lastOrder'].mode()[0],
}
db_mode_unknown = db.fillna(values)
db_mode_unknown.to_csv('database_mode_unknown.csv')

In [188]:
values = {
    'cMinPrice': db['cMinPrice'].astype(float).mean(),
    'cMaxPrice': db['cMaxPrice'].astype(float).mean(),
    'cSumPrice': db['cSumPrice'].astype(float).mean(),
    'bMinPrice': db['bMinPrice'].astype(float).mean(),
    'bMaxPrice': db['bMaxPrice'].astype(float).mean(),
    'bSumPrice': db['bSumPrice'].astype(float).mean(),
    'bStep': db['bStep'].astype(float).mean(),
    'onlineStatus': 'desconhecido',
    'availability': 'desconhecido',
    'customerNo': 'desconhecido',
    'maxVal': db['maxVal'].astype(float).mean(),
    'customerScore': db['customerScore'].astype(float).mean(),
    'accountLifetime': db['accountLifetime'].astype(float).mean(),
    'payments': db['payments'].astype(float).mean(),
    'age': db['age'].astype(float).mean(),
    'address': db['address'].astype(float).mean(),
    'lastOrder': db['lastOrder'].astype(float).mean(),
}
db_mean_unknown = db.fillna(values)
db_mean_unknown.to_csv('database_mean_unknown.csv')

In [189]:
values = {
    'cMinPrice': db['cMinPrice'].astype(float).mean(),
    'cMaxPrice': db['cMaxPrice'].astype(float).mean(),
    'cSumPrice': db['cSumPrice'].astype(float).mean(),
    'bMinPrice': db['bMinPrice'].astype(float).mean(),
    'bMaxPrice': db['bMaxPrice'].astype(float).mean(),
    'bSumPrice': db['bSumPrice'].astype(float).mean(),
    'bStep': db['bStep'].astype(float).mean(),
    'onlineStatus': db['onlineStatus'].mode()[0],
    'availability': db['availability'].mode()[0],
    'customerNo': db['customerNo'].mode()[0],
    'maxVal': db['maxVal'].astype(float).mean(),
    'customerScore': db['customerScore'].astype(float).mean(),
    'accountLifetime': db['accountLifetime'].astype(float).mean(),
    'payments': db['payments'].astype(float).mean(),
    'age': db['age'].astype(float).mean(),
    'address': db['address'].astype(float).mean(),
    'lastOrder': db['lastOrder'].astype(float).mean(),
}
db_mean_mode = db.fillna(values)
db_mean_mode.to_csv('database_mean_mode.csv')